<?php

namespace AppBundle\Repository;

/**
 * NotaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class NotaRepository extends \Doctrine\ORM\EntityRepository
{
}
